Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'

Rails/UniqueValidationWithoutIndex:
  Exclude:
    - 'app/models/position.rb'
    - 'app/models/department_worker.rb'
    - 'app/models/department.rb'
    - 'app/models/worker.rb'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/20240328182313_create_active_storage_tables.active_storage.rb'
    - 'app/controllers/workers_controller.rb'
    - 'app/controllers/department_workers_controller.rb'
    - 'app/controllers/vacations_controller.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/20240328182313_create_active_storage_tables.active_storage.rb'
    - 'db/migrate/20240321094741_create_workers.rb'  
    - 'app/controllers/department_workers_controller.rb' 
    - 'app/controllers/vacations_controller.rb' 

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/models/worker_spec.rb'
    - 'spec/models/department_worker_spec.rb'
    - 'spec/models/position_spec.rb'
    - 'spec/models/vacation_spec.rb'
    - 'spec/models/worker_position_spec.rb'
    - 'spec/requests/department_workers_spec.rb'
    - 'spec/requests/vacations_spec.rb'
    - 'spec/requests/vacations_spec.rb'
    - 'spec/requests/worker_positions_spec.rb'